### ISSUE TITLE
How do I resolve this error regarding blast result?

### ISSUE THREAD

**Issue by minyoung-lee** [lotts/GLASSgo_GI-Version#2]
Dear Authors,

When trying to run GLASSgo.py with NCBI nt.67 database, I am seeing this error:

Traceback (most recent call last):
  File "/home/mlee/Borellia_sRNA/GLASSgo/GLASSgo_GI-Version-master/GLASSgo.py", line 663, in <module>
    fasta_hits = extent_reads_from_blast_table(input_filename, blast_result, args.db, args.eValue)
  File "/home/mlee/Borellia_sRNA/GLASSgo/GLASSgo_GI-Version-master/GLASSgo.py", line 214, in extent_reads_from_blast_table
    coord1 = re.findall(":[a-z]*(\d*)-", lines[0])[0]
IndexError: list index out of range

I got a temporary file like "id.10894.tmp1" along with the error. 
It included my query sequence.
When I used my custom blast database, I did not see any error, and I also got the same temporary file.
How do I resolve the error?

Thanks,
Minyoung

**Comment by lotts** [comment]
Dear Minyoung,

many thanks for contacting us. Can you apply the following command on the command line?

For example (please replace the db path!):
blastdbcmd -db /media/biotools/db/blastdb/nt/nt -dbtype 'nucl' -entry 38423799 -range 1-10 -strand 'plus'

It should return the following result:

>\>AP004312.1 Synechocystis sp. PCC 6803 plasmid pSYSG DNA, complete genome >CP003268.1 Synechocystis sp. PCC 6803 plasmid pSYSG_M, complete sequence
GATCTGACTA

Best regards
Steffen

**Comment by minyoung-lee** [comment]
Dear Steffen,

Thank you for the response.

I got an error as follows:
Error: [blastdbcmd] Entry not found: 38423799
Error: [blastdbcmd] Entry or entries not found in BLAST database

When I modified the entry as follows:
blastdbcmd -db /home/mlee/Downloads/nt67/nt.67 -dbtype 'nucl' -entry 'CP017634.1' -range 1-10 -strand 'plus'

I got the following result:
>CP017634.1 Peptococcaceae bacterium DCMF, complete genome
TTTTTCGCCC

What was wrong with the nt database?

Thanks,
Minyoung

**Comment by lotts** [comment]
Dear Minyoung!

After your response, I downloaded the latest NCBI nt database and applied the same query again and it worked. Please ensure that all downloaded database files (nt.00.* - nt.67.*) are in the same folder (/home/mlee/Downloads/nt/). After reordering the nt files the command looks like:

blastdbcmd -db /home/mlee/Downloads/nt/nt -dbtype 'nucl' -entry 38423799 -range 1-10 -strand 'plus'

Please give a try and let me know if it works or not :) .

Best,
Steffen

**Comment by minyoung-lee** [comment]
[5472414.zip](https://github.com/lotts/GLASSgo_GI-Version/files/2692033/5472414.zip)
Hi Steffen,

I am really sorry for the late response. 
Thank you very much for the comments.

I have downloaded all the nt.00* - nt.67.* files in the same folder and got the same result you mentioned above:
>AP004312.1 Synechocystis sp. PCC 6803 plasmid pSYSG DNA, complete genome >CP003268.1 Synechocystis sp. PCC 6803 plasmid pSYSG_M, complete sequence
GATCTGACTA

Then I tried my query again and still got the same error.
Here is my command and the error:
python3.6 /home/mlee/Borellia_sRNA/GLASSgo/GLASSgo_GI-Version-master/GLASSgo.py -d /home/mlee/blastdb/nt/nt -i ../SR0001

Traceback (most recent call last):
  File "/home/mlee/Borellia_sRNA/GLASSgo/GLASSgo_GI-Version-master/GLASSgo.py", line 663, in <module>
    fasta_hits = extent_reads_from_blast_table(input_filename, blast_result, args.db, args.eValue)
  File "/home/mlee/Borellia_sRNA/GLASSgo/GLASSgo_GI-Version-master/GLASSgo.py", line 214, in extent_reads_fro
    coord1 = re.findall(":[a-z]*(\d*)-", lines[0])[0]
IndexError: list index out of range

The input sRNA fasta file was as follows:
>SR0001
AAAATATTTAATGGATTCAAAAGTATTAGGACAAATCTTGCCAGAATTAAGTTTTTCAAGTATCATTTCAGAAAAAATTTTATCAACTTTAACATTCATAAGTTAAAACCAAAACCCTTAAAGAAAAGCTTATTAATATAAGCAAAAAAACAAATTTTTAAGTATAATAACATAAGTGGCTATACTATTGATTA


What I expected was the same result from the GLASSgo web server as follows:
>SR0001
AAAATATTTAATGGATTCAAAAGTATTAGGACAAATCTTGCCAGAATTAAGTTTTTCAAGTATCATTTCAGAAAAAATTTTATCAACTTTAACATTCATAAGTTAAAACCAAAACCCTTAAAGAAAAGCTTATTAATATAAGCAAAAAAACAAATTTTTAAGTATAATAACATAAGTGGCTATACTATTGATTA
>CP002312.1:3150-3343 Borrelia   burgdorferi JD1, complete genome-p.c.VAL:100.0%-taxID:521008
AAAATATTTAATGGATTCAAAAGTATTAGGACAAATCTTGCCAGAATTAAGTTTTTCAAGTATCATTTCAGAAAAAATTTTATCAACTTTAACATTCATAAGTTAAAACCAAAACCCTTAAAGAAAAGCTTATTAATATAAGCAAAAAAACAAATTTTTAAGTATAATAACATAAGTGGCTATACTATTGATTA
>CP003882.1:3134-3326 Borrelia afzelii   HLJ01, complete genome-p.c.VAL:74.09%-taxID:1239934
AAAATATTTGATAAATTCAAAATTACTAACCCCTATCTCGCCAGAATTAAGTTTTTTAAGTATCATTTCAGAAAAAATTTTATCAACTTTAACATTCATTAGTAAAAACCAAGACCTTTAATATAAAGGGAATTAATACAAGCAAAAAAATAAATTTTTAAGTATAATAAATATAAACTACCATATTATTTTG
... (33 more hits)

I have attached the result zip file as well.
[5472414.zip](https://github.com/lotts/GLASSgo_GI-Version/files/2692040/5472414.zip)

I used the default parameters except that I set 'Taxon selection' to Bacteria.

My ultimate goal is to search the query against all Borrelia burgdorferi genomes in NCBI with my custom genome (new Borrelia burgdorferi genomes). 
I mentioned at the beginning of this thread, when I used my custom blast database, I did not see any error, and I got a temporary file, but not any result.
I guess there should be a hit for this query because there is a 100% identical sequence from blast search (pident = 100%, alignment length = query length, evalue = 5.25E-098).

What causes these errors and why are the errors different?

Best,
Minyoung

**Comment by lotts** [comment]
Dear Minyoung,

many thanks for your response and yes I got the same error like you. Because there are no hits during the first BLAST search and therefore the sequence extraction procedure fails. I will try to fix the bug.

Best,
Steffen

**Comment by doglasp** [comment]
Hi, I am getting the same error. 

GLASSgo.py -d BLAST_NT/nt.85 -i SRNA_INPUT/cgb_00105.fasta -o output-cgb_00105.fasta
Traceback (most recent call last):
  File "/bin/GLASSgo.py", line 663, in <module>
    fasta_hits = extent_reads_from_blast_table(input_filename, blast_result, args.db, args.eValue)
  File "/bin/GLASSgo.py", line 214, in extent_reads_from_blast_table
    coord1 = re.findall(":[a-z]*(\d*)-", lines[0])[0]
IndexError: list index out of range

**Comment by lotts** [comment]
Hi,

please use the latest version of GLASSgo (https://github.com/lotts/GLASSgo_ACC-Version). Additionally, a Docker container is available and can directly be used (https://hub.docker.com/r/lotts/glassgo_acc_version).
